N = int(input())
next = str(N + 1)
previous = str(N - 1)
J = str(N)
O = str(next)
P = str(previous)
print('The next number for the number', J, 'is %s.'%O)
print('The previous number for the number', J, 'is %s.'%P)
